include: package:flutter_lints/flutter.yaml

linter:
  rules:
    sort_constructors_first: true
    public_member_api_docs: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    prefer_if_elements_to_conditional_expressions: false
    prefer_single_quotes: true
    always_specify_types: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    invalid_annotation_target: ignore
